apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nso-lsa-lower-2
  labels:
    app: nso-lsa-lower-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nso-lsa-lower-2
  template:
    metadata:
      labels:
        app: nso-lsa-lower-2
    spec:
      containers:
        - name: nso-lsa-lower-2
          image: containers.cisco.com/frjansso/nso-lsa:1.0
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          env:
            - name: NCS_JAVA_VM_OPTIONS 
              value: -Xms1G
            - name: NCS_IPC_PORT 
              value: "4571"
          volumeMounts:
            - mountPath: /root/nso-project
              name: lower-2
          readinessProbe:
            tcpSocket:
              port: 2024
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2024
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: lower-2
          hostPath:
            path: $PWD/nso-projects/22-layered-service-architecture/lower-nso-2
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nso-lsa-lower-2
spec:
  selector: 
    app: nso-lsa-lower-2
  ports:
    - protocol: TCP
      name: netconf
      port: 2024
      targetPort: 2024
