apiVersion: apps/v1
kind: Deployment
metadata:
  name: nso-depl
spec:
  selector:
    matchLabels:
      app: nso
  replicas: 1
  template:
    metadata:
      labels:
        app: nso
    spec:
      containers:
      - name: nso
        image: containers.cisco.com/frjansso/nso-system-base
